version: "3.8"

services:
  drone:
    build: .
    network_mode: "host"
    privileged: true
    group_add:
      - video
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/udev:/run/udev
      - log:/home/ros/log

volumes:
  log:
