version: "3.8"

services:
  drone:
    build: .
    network_mode: "host"
    privileged: true
    group_add:
      - video
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/udev:/run/udev
#      - ./qualisys/logs:/home/ros/Logs/logs
#      - ./mnt/src:/home/ros/ros2_ws/src
      - ./log:/home/ros/log
