version: "3.8"

services:
  drone:  
    build: .
    network_mode: "host"
    privileged: true
    group_add:
      - video
      - plugdev
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /run/udev:/run/udev
